// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhAXQBgLKm_4l81_bkvl7oafmqVjBHKm0',
    appId: '1:871889871600:android:64bc5be0addc5722341835',
    messagingSenderId: '871889871600',
    projectId: 'chargelanka-app',
    storageBucket: 'chargelanka-app.firebasestorage.app',
  );

  // Configure iOS values after adding GoogleService-Info.plist.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhAXQBgLKm_4l81_bkvl7oafmqVjBHKm0',
    appId: '1:871889871600:ios:0000000000000000000000',
    messagingSenderId: '871889871600',
    projectId: 'chargelanka-app',
    storageBucket: 'chargelanka-app.firebasestorage.app',
    iosBundleId: 'com.voltshare.voltshareSl',
  );
}
